FROM node:19.4-bullseye as build

RUN addgroup app && adduser -S -G app app

USER app

WORKDIR /usr/src/app

COPY --chown=app:app package.json pnpm-lock.yaml ./

RUN npm ci -g pnpm

RUN pnpm set store-dir /usr/src/app/.pnpm-store && pnpm install

COPY --chown=app:app . ./

EXPOSE 3000

ENV DB_PORT=5432

CMD ["pnpm", "run", "dev"]
# if this is for production, use RUN pnpm run build


# the below is mainly for production
###
FROM nginxinc/nginxinc/nginx-unprivileged:1.23-alpine-perl

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 8080