version: '3.8'

services:
  frontend:
    build:
      context: ./frontend # folder to find the docker-file
      dockerfile: Dockerfile.dev.react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/usr/src/app/:ro
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    # command: ["npm", "run", "dev"] - no need for this command, it's already in the Dockerfile

  backend:
    build:
      context: ./backend # folder to find the docker-file
      dockerfile: Dockerfile.dev.golang
    ports:
      - "4000:4000"
    volumes:
      - ./backend/src:/usr/src/app/:ro
    environment:
      - DB_PASS=1234
    depends_on:
      - db
    # command: ["go", "run", "main.go"] - no need for this command, it's already in the Dockerfile  

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=template_test_db
    volumes:
      - db-data:/var/lib/postgresql/data
  
  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=4mHs3@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db

volumes:
  db-data:


