name: hello world workflow
on:
  push:
    branches:
      - main
      - dev
  
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:
    inputs:
      hello_input:
        description: Saying hello
        required: true
        default: Hi there, saying hello world
      bye_world:
        description: Saying bye world
        required: true
        default: Sad to see you go, Bye world

defaults:
  run:
    shell: bash

jobs:
  hello_world_job:
    name: hello world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo branch
        uses: actions/checkout@v4
        
      - name: hello greetings
        run: |
          echo "${{github.event.inputs.hello_input}}"
        shell: bash
  
  bye_world_job:
    name: bye world
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo branch
        uses: actions/checkout@v4
      
      - name: bye message
        run: |
          echo "${{github.event.inputs.bye_world}}"
        shell: bash