name: hello & bye world workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main:
      - dev:
  workflow_dispatch:

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello
        run: echo "Hello World"
        shell: bash

  bye_world_job:
    name: A job to say bye
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Bye
        run: echo "Bye World"
        shell: bash