# Stage 1: Build stage
FROM golang:1.21 AS builder

# Add a non-root user
RUN addgroup -S app && adduser -S -G app app

# Set work directory
WORKDIR /usr/src/app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY --chown=app:app . ./

# Build the Go application
RUN go build -o final_app .
# if your go code is located in a different folder, e.g: ./cmd/app
# RUN go build -o app ./cmd/app

# Stage 2: Development stage
FROM golang:1.21

# Add a non-root user
RUN addgroup -S app && adduser -S -G app app

# Set work directory
WORKDIR /usr/src/app

# Copy the built application and any other necessary files
COPY --from=builder /usr/src/app/. ./

# Switch to the non-root user
USER app

# Expose the port
EXPOSE 4000

# Command to run the application
CMD ["./final_app"]
