FROM golang:1.25 

# For a development environment, you don’t need to add a non-root user (app).
# RUN addgroup -S app && adduser -S -G app app
# USER app

WORKDIR /usr/src/app

# Install Air globally
RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

# Expose the development port
EXPOSE 4000

# Run Air for hot reloading
CMD ["air"]