# Stage 1: Build stage
FROM golang:1.21 AS builder

RUN addgroup -S app && adduser -S -G app app

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN go build -o app ./cmd/app

# Stage 2: Development stage
FROM golang:1.21

RUN addgroup -S app && adduser -S -G app app

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app ./
RUN go install github.com/cosmtrek/air@latest

USER app

EXPOSE 8080

CMD ["air"]
