# Use the official Node.js image with Alpine (lightweight)
FROM node:24.2-alpine

# Create a group and a non-root user
RUN addgroup -S app && adduser -S -G app app

# Set work directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) to install dependencies
COPY package*.json ./

# Install the dependencies as the root user
RUN npm install

# Switch to the non-root user
USER app

# Copy the application source code
COPY --chown=app:app . .
# RUN chown -R app:app /usr/src/app  ## Change ownership of the application files to the non-root user

# Expose the port your application will run on
EXPOSE 4000

# Set the command to run your Node.js backend app
CMD ["npm", "run", "start"]
