---
doe: a deer, a female deer
ray: a drop of golden sun
pi: 3.14159
xmas: true
french_hens: 3
calling-birds:
  - huey
  - dewey
  - louie
  - fred
xmas-fifth-day:
  calling-birds: four
  french_hens: 3
  golden-rings: 5
  partridges:
    count: 1
    location: a peer tree
  turtle-doves: two