name: comment on issues

on:
  issues:
    types: [opened, edited, closed]

jobs:
  community_action:
    name: using community action
    runs-on: ubuntu-latest
    steps:
      - name: dump github event data
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(github.event, null, 2))
      
      - name: uses peter evans action to comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue_number: ${{ github.event.issue.number }}
          body: |
            hello from github actions
          reaction: "+1"